# Generated by Django 5.2.16 on 2026-08-06 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_slug_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='昵称')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱（可选）')),
                ('content', models.TextField(max_length=1000, verbose_name='评论内容')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], db_index=True, default='pending', max_length=10, verbose_name='审核状态')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='提交者 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='所属文章')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'db_table': 'blog_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['article', 'status'], name='idx_comment_art_status')],
            },
        ),
    ]
